name: pkg-pr-new

on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "!**"

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish preview packages
        run: pnpm dlx pkg-pr-new publish
